"""unique added to customers.name

Revision ID: 41b9f6e68d03
Revises: 95ba1debafa4
Create Date: 2024-04-25 11:27:32.100410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b9f6e68d03'
down_revision = '95ba1debafa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_customers_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_customers_name'), type_='unique')

    # ### end Alembic commands ###
