"""removed unique

Revision ID: 64cef8843bb3
Revises: cf4d2ddc60ba
Create Date: 2023-04-06 10:32:47.037119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cef8843bb3'
down_revision = 'cf4d2ddc60ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_products_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_products_name', ['name'])

    # ### end Alembic commands ###
