"""Edited Car model

Revision ID: 1984a3611399
Revises: ee8178caac7e
Create Date: 2024-01-09 10:15:34.310640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1984a3611399'
down_revision = 'ee8178caac7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cars', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('year')

    # ### end Alembic commands ###
