"""Initial tables

Revision ID: 12986651e16b
Revises: 
Create Date: 2024-04-22 10:19:52.106066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12986651e16b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yoyos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yoyos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yoyos')
    # ### end Alembic commands ###
