"""added

Revision ID: 2fee81a47c74
Revises: 57a0a98d9c5c
Create Date: 2024-08-05 10:23:41.879217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fee81a47c74'
down_revision = '57a0a98d9c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laptop', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computers', schema=None) as batch_op:
        batch_op.drop_column('laptop')

    # ### end Alembic commands ###
