"""added column

Revision ID: 388ef452512e
Revises: 576ab8609fc5
Create Date: 2024-01-08 10:56:47.488076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388ef452512e'
down_revision = '576ab8609fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets_table', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
