"""empty message

Revision ID: 3a0a33fe0508
Revises: 2fee81a47c74
Create Date: 2024-08-05 10:34:30.827195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0a33fe0508'
down_revision = '2fee81a47c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aesthetics', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computers', schema=None) as batch_op:
        batch_op.drop_column('aesthetics')

    # ### end Alembic commands ###
