"""Added column and added nullable

Revision ID: 576ab8609fc5
Revises: 3da1c8ad8a88
Create Date: 2024-01-08 10:48:56.958545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576ab8609fc5'
down_revision = '3da1c8ad8a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets_table', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('color')

    # ### end Alembic commands ###
