"""Create table computers

Revision ID: 57a0a98d9c5c
Revises: 
Create Date: 2024-08-05 10:14:26.973040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a0a98d9c5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('memory', sa.String(), nullable=True),
    sa.Column('gpu', sa.String(), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_computers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computers')
    # ### end Alembic commands ###
