"""Changed column code to student_code

Revision ID: 64dc362b9e6f
Revises: ad062f7bf88d
Create Date: 2023-07-03 10:32:55.778158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dc362b9e6f'
down_revision = 'ad062f7bf88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_code', sa.Integer(), nullable=True))
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.INTEGER(), nullable=True))
        batch_op.drop_column('student_code')

    # ### end Alembic commands ###
