"""Corrected spelling

Revision ID: 6d59c7df92ff
Revises: 8a31a44fa0fc
Create Date: 2023-04-04 10:14:34.497459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d59c7df92ff'
down_revision = '8a31a44fa0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered', sa.Boolean(), nullable=True))
        batch_op.drop_column('registred')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registred', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('registered')

    # ### end Alembic commands ###
