"""empty message

Revision ID: 78ab4800a10e
Revises: e6eb4da8abc8
Create Date: 2024-04-22 10:24:53.221586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ab4800a10e'
down_revision = 'e6eb4da8abc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoyos', schema=None) as batch_op:
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoyos', schema=None) as batch_op:
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
