"""empty message

Revision ID: 918988817093
Revises: e42f02d9030b
Create Date: 2024-04-22 11:25:39.170191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918988817093'
down_revision = 'e42f02d9030b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoyos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_in_inches', sa.String(), nullable=True))
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoyos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('size_in_inches')

    # ### end Alembic commands ###
