"""Unique

Revision ID: aa4986fed28e
Revises: 6d59c7df92ff
Create Date: 2023-04-04 10:15:41.959931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4986fed28e'
down_revision = '6d59c7df92ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_vehicles_make'), ['make'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vehicles_make'), type_='unique')

    # ### end Alembic commands ###
