"""Edited students table

Revision ID: ad062f7bf88d
Revises: 2aaa56679fdc
Create Date: 2023-07-03 10:29:07.839096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad062f7bf88d'
down_revision = '2aaa56679fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('school')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
