"""remove column

Revision ID: bd101ebf7e84
Revises: 388ef452512e
Create Date: 2024-01-08 10:57:29.738636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd101ebf7e84'
down_revision = '388ef452512e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets_table', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
