"""empty message

Revision ID: e6eb4da8abc8
Revises: 12986651e16b
Create Date: 2024-04-22 10:21:55.973685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6eb4da8abc8'
down_revision = '12986651e16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoyos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoyos', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
