"""Create tables

Revision ID: c22a358515cd
Revises: e6d3aa6218c3
Create Date: 2024-08-06 10:24:40.055641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22a358515cd'
down_revision = 'e6d3aa6218c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_of_origin', sa.String(), nullable=True))
        batch_op.drop_column('coo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coo', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('country_of_origin')

    # ### end Alembic commands ###
