"""Create tables

Revision ID: e6d3aa6218c3
Revises: 7fb5901daa23
Create Date: 2024-08-06 10:24:08.162118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d3aa6218c3'
down_revision = '7fb5901daa23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coo', sa.String(), nullable=True))
        batch_op.drop_column('country_of_origin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_of_origin', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('coo')

    # ### end Alembic commands ###
