"""empty message

Revision ID: f86ef9e379bc
Revises: c1eabf0a1375
Create Date: 2024-04-23 11:11:06.678883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86ef9e379bc'
down_revision = 'c1eabf0a1375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_lectures_teacher_id_teachers'), 'teachers', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lectures_teacher_id_teachers'), type_='foreignkey')

    # ### end Alembic commands ###
