"""Adding more columns

Revision ID: 2d8d9b9b7740
Revises: a281cad18b75
Create Date: 2023-07-05 10:09:12.383003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8d9b9b7740'
down_revision = 'a281cad18b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('student_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_students_student_code'), ['student_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_students_student_code'), type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('student_code')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
