"""Adding more columns

Revision ID: 566d65febcbc
Revises: 2d8d9b9b7740
Create Date: 2023-07-05 10:15:30.193931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566d65febcbc'
down_revision = '2d8d9b9b7740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('emergency_email')

    # ### end Alembic commands ###
