"""empty message

Revision ID: 6ad0ab8281f6
Revises: 07828170b4a0
Create Date: 2024-08-07 11:00:01.604522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad0ab8281f6'
down_revision = '07828170b4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chef_id', sa.Integer(), nullable=True),
    sa.Column('pastry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['chefs.id'], name=op.f('fk_recipes_chef_id_chefs')),
    sa.ForeignKeyConstraint(['pastry_id'], ['pastries.id'], name=op.f('fk_recipes_pastry_id_pastries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_chefs_phone'), ['phone'])

    with op.batch_alter_table('pastries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pastries_chef_id_chefs', type_='foreignkey')
        batch_op.drop_column('chef_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chef_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_pastries_chef_id_chefs', 'chefs', ['chef_id'], ['id'])

    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_chefs_phone'), type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('recipes')
    # ### end Alembic commands ###
