"""Changed column type

Revision ID: 88362f49ae46
Revises: 28b6d4a446ae
Create Date: 2023-07-05 10:28:03.272219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88362f49ae46'
down_revision = '28b6d4a446ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
