"""Create tables

Revision ID: 9dedc0cb5b45
Revises: 222c0eafd677
Create Date: 2023-04-05 10:43:41.291318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dedc0cb5b45'
down_revision = '222c0eafd677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_schedules_student_id_students'), 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_schedules_teacher_id_teachers'), 'teachers', ['teacher_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_code', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_students_student_code'), ['student_code'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_email', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('emergency_email')
        batch_op.drop_column('email')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_students_student_code'), type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('student_code')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_schedules_teacher_id_teachers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_schedules_student_id_students'), type_='foreignkey')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
