"""Inital tables

Revision ID: d974ad3a518e
Revises: 
Create Date: 2024-04-24 10:19:29.253534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd974ad3a518e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alliances'))
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capital', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries'))
    )
    op.create_table('treaties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('alliance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], name=op.f('fk_treaties_alliance_id_alliances')),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_treaties_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treaties'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treaties')
    op.drop_table('countries')
    op.drop_table('alliances')
    # ### end Alembic commands ###
